### ISSUE TITLE
BO2: Error loading script

### ISSUE THREAD

**Issue by Miketaviuos** [DoktorSAS/VanityTS#2]
### Black Ops 2 Vanity TS
Getting an error when loading the script. This is caused by there being a DestroyOnEndGame() function on line 619 and one on line 1843. I just removed the one on 1842 but it should probably be updated here on Github so people who want to use this script can without any problem on first download.
![image](https://github.com/DoktorSAS/VanityTS/assets/122772498/35030efb-2429-4db7-a327-2176cd7d6cd0)

**Comment by DoktorSAS** [comment]
Solved. 
It was a duplicted definition of the same function
